groups:
  - name: application-alerts
    rules:

      - alert: HighErrorRate
        expr: |
          (
            sum(rate(app_http_requests_total{status=~"5.."}[5m]))
            /
            sum(rate(app_http_requests_total[5m]))
          ) * 100 > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High Error Rate Detected"
          description: "Error rate is above 5% for 2 minutes."

      - alert: HighLatency
        expr: |
          histogram_quantile(
            0.95,
            sum(rate(app_http_request_duration_seconds_bucket[5m])) by (le)
          ) > 1.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Latency Detected"
          description: "P95 latency is above 1.5 seconds."

  - name: infrastructure-alerts
    rules:
      - alert: ECSHighCPUUsage
        expr: |
          aws_ecs_cpuutilization_average{cluster_name="my-ecs-cluster"} > 80
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High ECS CPU Usage"
          description: "CPU utilization above 80% for ECS service {{ $labels.service_name }} in cluster {{ $labels.cluster_name }} for 2 minutes."