FROM prom/prometheus:latest

COPY prometheus.yml /etc/prometheus/prometheus.yml
COPY alerts.yml /etc/prometheus/alerts.yml

EXPOSE 9090

CMD ["--config.file=/etc/prometheus/prometheus.yml","--web.route-prefix=/prometheus","--web.external-url=/prometheus"]