global:
  scrape_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager.monitoring.local:9093

scrape_configs:

- job_name: "prometheus"
  metrics_path: /prometheus/metrics
  static_configs:
    - targets: ["localhost:9090"]


- job_name: "ecs-services"
  metrics_path: /metrics
  dns_sd_configs:
    - names:
        - myapp.monitoring.local
      type: "A"
      port: 5000

  relabel_configs:
    - source_labels: [__address__]
      target_label: instance