global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "uma80390@gmail.com"
  smtp_auth_username: "uma80390@gmail.com"
  smtp_auth_password: "kjmy bnky wmqh xguu"
  smtp_require_tls: true

route:
  receiver: "email-notifications"

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "adabala.um@gmail.com"
        send_resolved: true